option(ENABLE_LTO "Enable interprocedural optimization (LTO/IPO)" OFF)

set(PGO_MODE "OFF" CACHE STRING "PGO mode: OFF, GENERATE, or USE")
set_property(CACHE PGO_MODE PROPERTY STRINGS OFF GENERATE USE)
set(PGO_DATA_DIR "${CMAKE_BINARY_DIR}/pgo-data" CACHE PATH "Directory used for GCC PGO profiles")

set(_valid_pgo_modes OFF GENERATE USE)
if(NOT PGO_MODE IN_LIST _valid_pgo_modes)
  message(FATAL_ERROR "Invalid PGO_MODE='${PGO_MODE}'. Valid values: OFF, GENERATE, USE")
endif()

if(NOT PGO_MODE STREQUAL "OFF" AND NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  message(FATAL_ERROR "PGO_MODE currently supports GNU C++ compiler only. Detected: ${CMAKE_CXX_COMPILER_ID}")
endif()

set(TINYCACHE_PGO_COMPILE_OPTIONS)
set(TINYCACHE_PGO_LINK_OPTIONS)
if(PGO_MODE STREQUAL "GENERATE")
  list(APPEND TINYCACHE_PGO_COMPILE_OPTIONS "-fprofile-generate=${PGO_DATA_DIR}")
  list(APPEND TINYCACHE_PGO_LINK_OPTIONS "-fprofile-generate=${PGO_DATA_DIR}")
  message(STATUS "PGO mode: GENERATE (${PGO_DATA_DIR})")
elseif(PGO_MODE STREQUAL "USE")
  list(APPEND TINYCACHE_PGO_COMPILE_OPTIONS "-fprofile-use=${PGO_DATA_DIR}" "-fprofile-correction")
  list(APPEND TINYCACHE_PGO_LINK_OPTIONS "-fprofile-use=${PGO_DATA_DIR}" "-fprofile-correction")
  message(STATUS "PGO mode: USE (${PGO_DATA_DIR})")
endif()

set(TINYCACHE_LTO_ENABLED FALSE)
if(ENABLE_LTO)
  include(CheckIPOSupported)
  check_ipo_supported(RESULT _ipo_supported OUTPUT _ipo_error)
  if(_ipo_supported)
    set(TINYCACHE_LTO_ENABLED TRUE)
    message(STATUS "LTO/IPO is enabled")
  else()
    message(WARNING "ENABLE_LTO=ON but IPO/LTO is not supported: ${_ipo_error}")
  endif()
endif()

function(tinycache_apply_optimizations target_name)
  if(TINYCACHE_LTO_ENABLED)
    set_property(TARGET ${target_name} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
  endif()

  if(TINYCACHE_PGO_COMPILE_OPTIONS)
    target_compile_options(${target_name} PRIVATE ${TINYCACHE_PGO_COMPILE_OPTIONS})
  endif()

  if(TINYCACHE_PGO_LINK_OPTIONS)
    get_target_property(_target_type ${target_name} TYPE)
    if(NOT _target_type STREQUAL "STATIC_LIBRARY")
      target_link_options(${target_name} PRIVATE ${TINYCACHE_PGO_LINK_OPTIONS})
    endif()
  endif()
endfunction()
